#playbook入口文件
#Site Configuration
#此站点中部署了整个应用程序堆栈
---
#将通用配置应用于所有主机
- hosts: all
  roles:
  - common

- hosts: dbservers
  roles:
  - db                             #引用roles里的db角色
  tags:                            #通过-t 命令传递对应的参数，并指定playbook入口
  - db
#webservers需要部署两个环境，因此配置了两个角色
- hosts: webservers
  roles:
  - base-apache
  - web
  tags:
  - web
#配置部署负载均衡器
- hosts: lbservers
  roles:
  - haproxy
  tags:
  - lb
#配置部署监控节点
- hosts: monitoring
  roles:
  - base-apache
  - nagios
  tags:
  - monitoring
