---
# file:roles/common/tasks/main.yml

- name: ensure deploy group exist
  group: name={{ deploy_group }} gid={{ deploy_gid }} state=present

- name: ensure deploy user exist
  user: name={{ deploy_user }} uid={{ deploy_uid }} group={{ deploy_group }} state=present createhome=yes
