#表示文件是yaml文件
---
#all表示所有主机，组名
- hosts: all
#所有tasks集合
  tasks:
#定义使用模块及相关命令
  - name: install nginx
    apt: name=nginx state=present
#validate用于nginx的验证命令，
#notify用于测试同步的nginx.conf是否发生变化，如果发生变化，会触发handlers下的模块
  - name: copy nginx.conf
    template: src=/etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644 validate='nginx -t -c %s'
    notify:
      - ReStart nginx service
  handlers:
  - name: ReStart nginx service
    service: name=nginx state=restarted

#ansible-playbook nginx.yaml --syntax-check     检测nginx.yaml文件书写是否正确
#ansible-playbook nginx.yaml --list-hosts       检测nginx.yaml文件host表中有哪些机器

注：后续想改变nginx配置文件。只需改变（本机）src=/etc/nginx/nginx.conf文件即可
